const getMovies = () => {
  return [
    {
      id: 1,
      title: "인센션",
      year: "2010",
      director: "크리스토퍼 놀란",
      description: "현실과 꿈의 경계를 넘나드는 액션 블록버스터",
      imageUrl: "",
    },
    {
      id: 2,
      title: "기생충",
      year: "2019",
      director: "봉준호",
      description: "두 가족의 만남으로 시작되는 예기치 못한 사건",
      imageUrl: "",
    },
    {
      id: 3,
      title: "어벤져서: 엔드게임",
      year: "2019",
      director: "안소니 루소",
      description: "마블 시네마틱 유니버스의 대단원",
      imageUrl: "",
    },
    {
      id: 4,
      title: "조커",
      year: "2019",
      director: "토드 필립스",
      description: "조커의 소중한 삶을 그린 영화",
      imageUrl: "",
    },
    {
      id: 5,
      title: "라라랜드",
      year: "2016",
      director: "대니 보일",
      description: "라라랜드에서 행복한 삶을 꿈꾸는 두 사람",
      imageUrl: "",
    },
    {
      id: 6,
      title: "타이타닉",
      year: "1997",
      director: "제임스 카메론",
      description: "침몰하는 타이타닉호에서 펼쳐지는 비극적 로맨스",
      imageUrl: "",
    },
    {
      id: 7,
      title: "올드보이",
      year: "2003",
      director: "박찬욱",
      description: "15년간 감금된 남자의 복수 이야기",
      imageUrl: "",
    },
    {
      id: 8,
      title: "인터스텔라",
      year: "2014",
      director: "크리스토퍼 놀란",
      description: "인류의 생존을 위한 우주 탐험 서사시",
      imageUrl: "",
    },
    {
      id: 9,
      title: "아바타",
      year: "2009",
      director: "제임스 카메론",
      description: "판도라 행성에서 벌어지는 환상적인 모험",
      imageUrl: "",
    },
    {
      id: 10,
      title: "부산행",
      year: "2016",
      director: "연상호",
      description: "좀비 바이러스가 창궐한 한국을 배경으로 한 스릴러",
      imageUrl: "",
    },
  ];
};

export default getMovies;
